//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18034.
// 
#pragma warning disable 1591

namespace CrawlWave.Scheduler.CrawlWave.Server {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CrawlWaveServerSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternetUrl))]
    public partial class CrawlWaveServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback IsAliveOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClientComputerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCrawlResultsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCrawlResultsRawOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback RegisterUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendBannedHostsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendLatestVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendServersOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUpdatedVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUrlsToCrawlOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendUserStatisticsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CrawlWaveServer() {
            this.Url = global::CrawlWave.Scheduler.Properties.Settings.Default.CrawlWave_Scheduler_CrawlWave_Server_CrawlWaveServer;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event IsAliveCompletedEventHandler IsAliveCompleted;
        
        /// <remarks/>
        public event GetClientComputerInfoCompletedEventHandler GetClientComputerInfoCompleted;
        
        /// <remarks/>
        public event GetCrawlResultsCompletedEventHandler GetCrawlResultsCompleted;
        
        /// <remarks/>
        public event GetCrawlResultsRawCompletedEventHandler GetCrawlResultsRawCompleted;
        
        /// <remarks/>
        public event RegisterClientCompletedEventHandler RegisterClientCompleted;
        
        /// <remarks/>
        public event RegisterUserCompletedEventHandler RegisterUserCompleted;
        
        /// <remarks/>
        public event SendBannedHostsCompletedEventHandler SendBannedHostsCompleted;
        
        /// <remarks/>
        public event SendLatestVersionCompletedEventHandler SendLatestVersionCompleted;
        
        /// <remarks/>
        public event SendServersCompletedEventHandler SendServersCompleted;
        
        /// <remarks/>
        public event SendUpdatedVersionCompletedEventHandler SendUpdatedVersionCompleted;
        
        /// <remarks/>
        public event SendUrlsToCrawlCompletedEventHandler SendUrlsToCrawlCompleted;
        
        /// <remarks/>
        public event SendUserStatisticsCompletedEventHandler SendUserStatisticsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IsAlive", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool IsAlive() {
            object[] results = this.Invoke("IsAlive", new object[0]);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginIsAlive(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("IsAlive", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndIsAlive(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsAliveAsync() {
            this.IsAliveAsync(null);
        }
        
        /// <remarks/>
        public void IsAliveAsync(object userState) {
            if ((this.IsAliveOperationCompleted == null)) {
                this.IsAliveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsAliveOperationCompleted);
            }
            this.InvokeAsync("IsAlive", new object[0], this.IsAliveOperationCompleted, userState);
        }
        
        private void OnIsAliveOperationCompleted(object arg) {
            if ((this.IsAliveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsAliveCompleted(this, new IsAliveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClientComputerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException GetClientComputerInfo(ClientInfo ci, CWComputerInfo info) {
            object[] results = this.Invoke("GetClientComputerInfo", new object[] {
                        ci,
                        info});
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetClientComputerInfo(ClientInfo ci, CWComputerInfo info, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetClientComputerInfo", new object[] {
                        ci,
                        info}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndGetClientComputerInfo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void GetClientComputerInfoAsync(ClientInfo ci, CWComputerInfo info) {
            this.GetClientComputerInfoAsync(ci, info, null);
        }
        
        /// <remarks/>
        public void GetClientComputerInfoAsync(ClientInfo ci, CWComputerInfo info, object userState) {
            if ((this.GetClientComputerInfoOperationCompleted == null)) {
                this.GetClientComputerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClientComputerInfoOperationCompleted);
            }
            this.InvokeAsync("GetClientComputerInfo", new object[] {
                        ci,
                        info}, this.GetClientComputerInfoOperationCompleted, userState);
        }
        
        private void OnGetClientComputerInfoOperationCompleted(object arg) {
            if ((this.GetClientComputerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClientComputerInfoCompleted(this, new GetClientComputerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCrawlResults", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException GetCrawlResults(ClientInfo ci, UrlCrawlData[] data) {
            object[] results = this.Invoke("GetCrawlResults", new object[] {
                        ci,
                        data});
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCrawlResults(ClientInfo ci, UrlCrawlData[] data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCrawlResults", new object[] {
                        ci,
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndGetCrawlResults(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void GetCrawlResultsAsync(ClientInfo ci, UrlCrawlData[] data) {
            this.GetCrawlResultsAsync(ci, data, null);
        }
        
        /// <remarks/>
        public void GetCrawlResultsAsync(ClientInfo ci, UrlCrawlData[] data, object userState) {
            if ((this.GetCrawlResultsOperationCompleted == null)) {
                this.GetCrawlResultsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCrawlResultsOperationCompleted);
            }
            this.InvokeAsync("GetCrawlResults", new object[] {
                        ci,
                        data}, this.GetCrawlResultsOperationCompleted, userState);
        }
        
        private void OnGetCrawlResultsOperationCompleted(object arg) {
            if ((this.GetCrawlResultsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCrawlResultsCompleted(this, new GetCrawlResultsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCrawlResultsRaw", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException GetCrawlResultsRaw(ClientInfo ci, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] data) {
            object[] results = this.Invoke("GetCrawlResultsRaw", new object[] {
                        ci,
                        data});
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGetCrawlResultsRaw(ClientInfo ci, byte[] data, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetCrawlResultsRaw", new object[] {
                        ci,
                        data}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndGetCrawlResultsRaw(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void GetCrawlResultsRawAsync(ClientInfo ci, byte[] data) {
            this.GetCrawlResultsRawAsync(ci, data, null);
        }
        
        /// <remarks/>
        public void GetCrawlResultsRawAsync(ClientInfo ci, byte[] data, object userState) {
            if ((this.GetCrawlResultsRawOperationCompleted == null)) {
                this.GetCrawlResultsRawOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCrawlResultsRawOperationCompleted);
            }
            this.InvokeAsync("GetCrawlResultsRaw", new object[] {
                        ci,
                        data}, this.GetCrawlResultsRawOperationCompleted, userState);
        }
        
        private void OnGetCrawlResultsRawOperationCompleted(object arg) {
            if ((this.GetCrawlResultsRawCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCrawlResultsRawCompleted(this, new GetCrawlResultsRawCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException RegisterClient(ref ClientInfo ci, CWComputerInfo info) {
            object[] results = this.Invoke("RegisterClient", new object[] {
                        ci,
                        info});
            ci = ((ClientInfo)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegisterClient(ClientInfo ci, CWComputerInfo info, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegisterClient", new object[] {
                        ci,
                        info}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndRegisterClient(System.IAsyncResult asyncResult, out ClientInfo ci) {
            object[] results = this.EndInvoke(asyncResult);
            ci = ((ClientInfo)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterClientAsync(ClientInfo ci, CWComputerInfo info) {
            this.RegisterClientAsync(ci, info, null);
        }
        
        /// <remarks/>
        public void RegisterClientAsync(ClientInfo ci, CWComputerInfo info, object userState) {
            if ((this.RegisterClientOperationCompleted == null)) {
                this.RegisterClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterClientOperationCompleted);
            }
            this.InvokeAsync("RegisterClient", new object[] {
                        ci,
                        info}, this.RegisterClientOperationCompleted, userState);
        }
        
        private void OnRegisterClientOperationCompleted(object arg) {
            if ((this.RegisterClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterClientCompleted(this, new RegisterClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RegisterUser", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException RegisterUser(ref int ID, string username, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] password, string email) {
            object[] results = this.Invoke("RegisterUser", new object[] {
                        ID,
                        username,
                        password,
                        email});
            ID = ((int)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginRegisterUser(int ID, string username, byte[] password, string email, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("RegisterUser", new object[] {
                        ID,
                        username,
                        password,
                        email}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndRegisterUser(System.IAsyncResult asyncResult, out int ID) {
            object[] results = this.EndInvoke(asyncResult);
            ID = ((int)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void RegisterUserAsync(int ID, string username, byte[] password, string email) {
            this.RegisterUserAsync(ID, username, password, email, null);
        }
        
        /// <remarks/>
        public void RegisterUserAsync(int ID, string username, byte[] password, string email, object userState) {
            if ((this.RegisterUserOperationCompleted == null)) {
                this.RegisterUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRegisterUserOperationCompleted);
            }
            this.InvokeAsync("RegisterUser", new object[] {
                        ID,
                        username,
                        password,
                        email}, this.RegisterUserOperationCompleted, userState);
        }
        
        private void OnRegisterUserOperationCompleted(object arg) {
            if ((this.RegisterUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RegisterUserCompleted(this, new RegisterUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendBannedHosts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException SendBannedHosts(ClientInfo ci, out System.Data.DataSet data) {
            object[] results = this.Invoke("SendBannedHosts", new object[] {
                        ci});
            data = ((System.Data.DataSet)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendBannedHosts(ClientInfo ci, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendBannedHosts", new object[] {
                        ci}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndSendBannedHosts(System.IAsyncResult asyncResult, out System.Data.DataSet data) {
            object[] results = this.EndInvoke(asyncResult);
            data = ((System.Data.DataSet)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void SendBannedHostsAsync(ClientInfo ci) {
            this.SendBannedHostsAsync(ci, null);
        }
        
        /// <remarks/>
        public void SendBannedHostsAsync(ClientInfo ci, object userState) {
            if ((this.SendBannedHostsOperationCompleted == null)) {
                this.SendBannedHostsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendBannedHostsOperationCompleted);
            }
            this.InvokeAsync("SendBannedHosts", new object[] {
                        ci}, this.SendBannedHostsOperationCompleted, userState);
        }
        
        private void OnSendBannedHostsOperationCompleted(object arg) {
            if ((this.SendBannedHostsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendBannedHostsCompleted(this, new SendBannedHostsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendLatestVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException SendLatestVersion(ClientInfo ci, out string version) {
            object[] results = this.Invoke("SendLatestVersion", new object[] {
                        ci});
            version = ((string)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendLatestVersion(ClientInfo ci, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendLatestVersion", new object[] {
                        ci}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndSendLatestVersion(System.IAsyncResult asyncResult, out string version) {
            object[] results = this.EndInvoke(asyncResult);
            version = ((string)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void SendLatestVersionAsync(ClientInfo ci) {
            this.SendLatestVersionAsync(ci, null);
        }
        
        /// <remarks/>
        public void SendLatestVersionAsync(ClientInfo ci, object userState) {
            if ((this.SendLatestVersionOperationCompleted == null)) {
                this.SendLatestVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendLatestVersionOperationCompleted);
            }
            this.InvokeAsync("SendLatestVersion", new object[] {
                        ci}, this.SendLatestVersionOperationCompleted, userState);
        }
        
        private void OnSendLatestVersionOperationCompleted(object arg) {
            if ((this.SendLatestVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendLatestVersionCompleted(this, new SendLatestVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendServers", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException SendServers(ClientInfo ci, out System.Data.DataSet data) {
            object[] results = this.Invoke("SendServers", new object[] {
                        ci});
            data = ((System.Data.DataSet)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendServers(ClientInfo ci, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendServers", new object[] {
                        ci}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndSendServers(System.IAsyncResult asyncResult, out System.Data.DataSet data) {
            object[] results = this.EndInvoke(asyncResult);
            data = ((System.Data.DataSet)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void SendServersAsync(ClientInfo ci) {
            this.SendServersAsync(ci, null);
        }
        
        /// <remarks/>
        public void SendServersAsync(ClientInfo ci, object userState) {
            if ((this.SendServersOperationCompleted == null)) {
                this.SendServersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendServersOperationCompleted);
            }
            this.InvokeAsync("SendServers", new object[] {
                        ci}, this.SendServersOperationCompleted, userState);
        }
        
        private void OnSendServersOperationCompleted(object arg) {
            if ((this.SendServersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendServersCompleted(this, new SendServersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendUpdatedVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException SendUpdatedVersion(ClientInfo ci, string version, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] out byte[] data) {
            object[] results = this.Invoke("SendUpdatedVersion", new object[] {
                        ci,
                        version});
            data = ((byte[])(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendUpdatedVersion(ClientInfo ci, string version, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendUpdatedVersion", new object[] {
                        ci,
                        version}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndSendUpdatedVersion(System.IAsyncResult asyncResult, out byte[] data) {
            object[] results = this.EndInvoke(asyncResult);
            data = ((byte[])(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void SendUpdatedVersionAsync(ClientInfo ci, string version) {
            this.SendUpdatedVersionAsync(ci, version, null);
        }
        
        /// <remarks/>
        public void SendUpdatedVersionAsync(ClientInfo ci, string version, object userState) {
            if ((this.SendUpdatedVersionOperationCompleted == null)) {
                this.SendUpdatedVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUpdatedVersionOperationCompleted);
            }
            this.InvokeAsync("SendUpdatedVersion", new object[] {
                        ci,
                        version}, this.SendUpdatedVersionOperationCompleted, userState);
        }
        
        private void OnSendUpdatedVersionOperationCompleted(object arg) {
            if ((this.SendUpdatedVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUpdatedVersionCompleted(this, new SendUpdatedVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendUrlsToCrawl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException SendUrlsToCrawl(ClientInfo ci, out InternetUrlToCrawl[] data) {
            object[] results = this.Invoke("SendUrlsToCrawl", new object[] {
                        ci});
            data = ((InternetUrlToCrawl[])(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendUrlsToCrawl(ClientInfo ci, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendUrlsToCrawl", new object[] {
                        ci}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndSendUrlsToCrawl(System.IAsyncResult asyncResult, out InternetUrlToCrawl[] data) {
            object[] results = this.EndInvoke(asyncResult);
            data = ((InternetUrlToCrawl[])(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void SendUrlsToCrawlAsync(ClientInfo ci) {
            this.SendUrlsToCrawlAsync(ci, null);
        }
        
        /// <remarks/>
        public void SendUrlsToCrawlAsync(ClientInfo ci, object userState) {
            if ((this.SendUrlsToCrawlOperationCompleted == null)) {
                this.SendUrlsToCrawlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUrlsToCrawlOperationCompleted);
            }
            this.InvokeAsync("SendUrlsToCrawl", new object[] {
                        ci}, this.SendUrlsToCrawlOperationCompleted, userState);
        }
        
        private void OnSendUrlsToCrawlOperationCompleted(object arg) {
            if ((this.SendUrlsToCrawlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUrlsToCrawlCompleted(this, new SendUrlsToCrawlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendUserStatistics", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SerializedException SendUserStatistics(ClientInfo ci, out UserStatistics stats) {
            object[] results = this.Invoke("SendUserStatistics", new object[] {
                        ci});
            stats = ((UserStatistics)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginSendUserStatistics(ClientInfo ci, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendUserStatistics", new object[] {
                        ci}, callback, asyncState);
        }
        
        /// <remarks/>
        public SerializedException EndSendUserStatistics(System.IAsyncResult asyncResult, out UserStatistics stats) {
            object[] results = this.EndInvoke(asyncResult);
            stats = ((UserStatistics)(results[1]));
            return ((SerializedException)(results[0]));
        }
        
        /// <remarks/>
        public void SendUserStatisticsAsync(ClientInfo ci) {
            this.SendUserStatisticsAsync(ci, null);
        }
        
        /// <remarks/>
        public void SendUserStatisticsAsync(ClientInfo ci, object userState) {
            if ((this.SendUserStatisticsOperationCompleted == null)) {
                this.SendUserStatisticsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendUserStatisticsOperationCompleted);
            }
            this.InvokeAsync("SendUserStatistics", new object[] {
                        ci}, this.SendUserStatisticsOperationCompleted, userState);
        }
        
        private void OnSendUserStatisticsOperationCompleted(object arg) {
            if ((this.SendUserStatisticsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendUserStatisticsCompleted(this, new SendUserStatisticsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ClientInfo {
        
        private int userIDField;
        
        private System.Guid clientIDField;
        
        private string versionField;
        
        /// <remarks/>
        public int UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid ClientID {
            get {
                return this.clientIDField;
            }
            set {
                this.clientIDField = value;
            }
        }
        
        /// <remarks/>
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserStatistics {
        
        private System.DateTime registrationDateField;
        
        private int numClientsField;
        
        private long urlsAssignedField;
        
        private long urlsReturnedField;
        
        private System.DateTime lastActiveField;
        
        /// <remarks/>
        public System.DateTime RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        public int NumClients {
            get {
                return this.numClientsField;
            }
            set {
                this.numClientsField = value;
            }
        }
        
        /// <remarks/>
        public long UrlsAssigned {
            get {
                return this.urlsAssignedField;
            }
            set {
                this.urlsAssignedField = value;
            }
        }
        
        /// <remarks/>
        public long UrlsReturned {
            get {
                return this.urlsReturnedField;
            }
            set {
                this.urlsReturnedField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastActive {
            get {
                return this.lastActiveField;
            }
            set {
                this.lastActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternetUrlToIndex))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternetUrlToCrawl))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InternetUrl {
        
        private int idField;
        
        private string urlField;
        
        private byte[] mD5Field;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MD5 {
            get {
                return this.mD5Field;
            }
            set {
                this.mD5Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InternetUrlToIndex : InternetUrl {
        
        private bool flagRobotsField;
        
        private DomainFlagValue flagDomainField;
        
        private byte priorityField;
        
        /// <remarks/>
        public bool FlagRobots {
            get {
                return this.flagRobotsField;
            }
            set {
                this.flagRobotsField = value;
            }
        }
        
        /// <remarks/>
        public DomainFlagValue FlagDomain {
            get {
                return this.flagDomainField;
            }
            set {
                this.flagDomainField = value;
            }
        }
        
        /// <remarks/>
        public byte Priority {
            get {
                return this.priorityField;
            }
            set {
                this.priorityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DomainFlagValue {
        
        /// <remarks/>
        MustVisit,
        
        /// <remarks/>
        MustNotVisit,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class InternetUrlToCrawl : InternetUrl {
        
        private long cRCField;
        
        private DomainFlagValue flagDomainField;
        
        private bool flagFetchRobotsField;
        
        private string robotsDisallowedPathsField;
        
        /// <remarks/>
        public long CRC {
            get {
                return this.cRCField;
            }
            set {
                this.cRCField = value;
            }
        }
        
        /// <remarks/>
        public DomainFlagValue FlagDomain {
            get {
                return this.flagDomainField;
            }
            set {
                this.flagDomainField = value;
            }
        }
        
        /// <remarks/>
        public bool FlagFetchRobots {
            get {
                return this.flagFetchRobotsField;
            }
            set {
                this.flagFetchRobotsField = value;
            }
        }
        
        /// <remarks/>
        public string RobotsDisallowedPaths {
            get {
                return this.robotsDisallowedPathsField;
            }
            set {
                this.robotsDisallowedPathsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UrlCrawlData {
        
        private string urlField;
        
        private InternetUrlToCrawl urlToCrawlField;
        
        private int idField;
        
        private byte[] mD5Field;
        
        private bool updatedField;
        
        private bool redirectedField;
        
        private bool redirectedFlagRobotsField;
        
        private DomainFlagValue redirectedFlagDomainField;
        
        private byte redirectedPriorityField;
        
        private long cRCField;
        
        private bool flagFetchRobotsField;
        
        private string robotsDisallowedPathsField;
        
        private HttpStatusCode httpStatusCodeField;
        
        private string dataField;
        
        private System.DateTime timeStampField;
        
        private int retrievalTimeField;
        
        private InternetUrlToIndex[] outLinksField;
        
        /// <remarks/>
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
        
        /// <remarks/>
        public InternetUrlToCrawl UrlToCrawl {
            get {
                return this.urlToCrawlField;
            }
            set {
                this.urlToCrawlField = value;
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] MD5 {
            get {
                return this.mD5Field;
            }
            set {
                this.mD5Field = value;
            }
        }
        
        /// <remarks/>
        public bool Updated {
            get {
                return this.updatedField;
            }
            set {
                this.updatedField = value;
            }
        }
        
        /// <remarks/>
        public bool Redirected {
            get {
                return this.redirectedField;
            }
            set {
                this.redirectedField = value;
            }
        }
        
        /// <remarks/>
        public bool RedirectedFlagRobots {
            get {
                return this.redirectedFlagRobotsField;
            }
            set {
                this.redirectedFlagRobotsField = value;
            }
        }
        
        /// <remarks/>
        public DomainFlagValue RedirectedFlagDomain {
            get {
                return this.redirectedFlagDomainField;
            }
            set {
                this.redirectedFlagDomainField = value;
            }
        }
        
        /// <remarks/>
        public byte RedirectedPriority {
            get {
                return this.redirectedPriorityField;
            }
            set {
                this.redirectedPriorityField = value;
            }
        }
        
        /// <remarks/>
        public long CRC {
            get {
                return this.cRCField;
            }
            set {
                this.cRCField = value;
            }
        }
        
        /// <remarks/>
        public bool FlagFetchRobots {
            get {
                return this.flagFetchRobotsField;
            }
            set {
                this.flagFetchRobotsField = value;
            }
        }
        
        /// <remarks/>
        public string RobotsDisallowedPaths {
            get {
                return this.robotsDisallowedPathsField;
            }
            set {
                this.robotsDisallowedPathsField = value;
            }
        }
        
        /// <remarks/>
        public HttpStatusCode HttpStatusCode {
            get {
                return this.httpStatusCodeField;
            }
            set {
                this.httpStatusCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public int RetrievalTime {
            get {
                return this.retrievalTimeField;
            }
            set {
                this.retrievalTimeField = value;
            }
        }
        
        /// <remarks/>
        public InternetUrlToIndex[] OutLinks {
            get {
                return this.outLinksField;
            }
            set {
                this.outLinksField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum HttpStatusCode {
        
        /// <remarks/>
        Continue,
        
        /// <remarks/>
        SwitchingProtocols,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        NonAuthoritativeInformation,
        
        /// <remarks/>
        NoContent,
        
        /// <remarks/>
        ResetContent,
        
        /// <remarks/>
        PartialContent,
        
        /// <remarks/>
        MultipleChoices,
        
        /// <remarks/>
        Ambiguous,
        
        /// <remarks/>
        MovedPermanently,
        
        /// <remarks/>
        Moved,
        
        /// <remarks/>
        Found,
        
        /// <remarks/>
        Redirect,
        
        /// <remarks/>
        SeeOther,
        
        /// <remarks/>
        RedirectMethod,
        
        /// <remarks/>
        NotModified,
        
        /// <remarks/>
        UseProxy,
        
        /// <remarks/>
        Unused,
        
        /// <remarks/>
        TemporaryRedirect,
        
        /// <remarks/>
        RedirectKeepVerb,
        
        /// <remarks/>
        BadRequest,
        
        /// <remarks/>
        Unauthorized,
        
        /// <remarks/>
        PaymentRequired,
        
        /// <remarks/>
        Forbidden,
        
        /// <remarks/>
        NotFound,
        
        /// <remarks/>
        MethodNotAllowed,
        
        /// <remarks/>
        NotAcceptable,
        
        /// <remarks/>
        ProxyAuthenticationRequired,
        
        /// <remarks/>
        RequestTimeout,
        
        /// <remarks/>
        Conflict,
        
        /// <remarks/>
        Gone,
        
        /// <remarks/>
        LengthRequired,
        
        /// <remarks/>
        PreconditionFailed,
        
        /// <remarks/>
        RequestEntityTooLarge,
        
        /// <remarks/>
        RequestUriTooLong,
        
        /// <remarks/>
        UnsupportedMediaType,
        
        /// <remarks/>
        RequestedRangeNotSatisfiable,
        
        /// <remarks/>
        ExpectationFailed,
        
        /// <remarks/>
        InternalServerError,
        
        /// <remarks/>
        NotImplemented,
        
        /// <remarks/>
        BadGateway,
        
        /// <remarks/>
        ServiceUnavailable,
        
        /// <remarks/>
        GatewayTimeout,
        
        /// <remarks/>
        HttpVersionNotSupported,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SerializedException {
        
        private string typeField;
        
        private string messageField;
        
        private string stackTraceField;
        
        /// <remarks/>
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string StackTrace {
            get {
                return this.stackTraceField;
            }
            set {
                this.stackTraceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CWComputerInfo {
        
        private string cPUTypeField;
        
        private int rAMSizeField;
        
        private int hDDSpaceField;
        
        private CWConnectionSpeed connectionSpeedField;
        
        /// <remarks/>
        public string CPUType {
            get {
                return this.cPUTypeField;
            }
            set {
                this.cPUTypeField = value;
            }
        }
        
        /// <remarks/>
        public int RAMSize {
            get {
                return this.rAMSizeField;
            }
            set {
                this.rAMSizeField = value;
            }
        }
        
        /// <remarks/>
        public int HDDSpace {
            get {
                return this.hDDSpaceField;
            }
            set {
                this.hDDSpaceField = value;
            }
        }
        
        /// <remarks/>
        public CWConnectionSpeed ConnectionSpeed {
            get {
                return this.connectionSpeedField;
            }
            set {
                this.connectionSpeedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18034")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum CWConnectionSpeed {
        
        /// <remarks/>
        Unknown,
        
        /// <remarks/>
        Modem56K,
        
        /// <remarks/>
        ISDN64K,
        
        /// <remarks/>
        ISDN128K,
        
        /// <remarks/>
        DSL256K,
        
        /// <remarks/>
        DSL384K,
        
        /// <remarks/>
        DSL512K,
        
        /// <remarks/>
        DSL1M,
        
        /// <remarks/>
        T1,
        
        /// <remarks/>
        T3,
        
        /// <remarks/>
        Fiber,
        
        /// <remarks/>
        ATM,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void IsAliveCompletedEventHandler(object sender, IsAliveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsAliveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsAliveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetClientComputerInfoCompletedEventHandler(object sender, GetClientComputerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClientComputerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClientComputerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCrawlResultsCompletedEventHandler(object sender, GetCrawlResultsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCrawlResultsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCrawlResultsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCrawlResultsRawCompletedEventHandler(object sender, GetCrawlResultsRawCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCrawlResultsRawCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCrawlResultsRawCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RegisterClientCompletedEventHandler(object sender, RegisterClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public ClientInfo ci {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ClientInfo)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RegisterUserCompletedEventHandler(object sender, RegisterUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RegisterUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RegisterUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendBannedHostsCompletedEventHandler(object sender, SendBannedHostsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendBannedHostsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendBannedHostsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendLatestVersionCompletedEventHandler(object sender, SendLatestVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendLatestVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendLatestVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string version {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendServersCompletedEventHandler(object sender, SendServersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendServersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendServersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendUpdatedVersionCompletedEventHandler(object sender, SendUpdatedVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUpdatedVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUpdatedVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public byte[] data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendUrlsToCrawlCompletedEventHandler(object sender, SendUrlsToCrawlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUrlsToCrawlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUrlsToCrawlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public InternetUrlToCrawl[] data {
            get {
                this.RaiseExceptionIfNecessary();
                return ((InternetUrlToCrawl[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendUserStatisticsCompletedEventHandler(object sender, SendUserStatisticsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendUserStatisticsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendUserStatisticsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SerializedException Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SerializedException)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public UserStatistics stats {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserStatistics)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591